### ISSUE TITLE
Mordant 2.0

### ISSUE THREAD

**Issue by ajalt** [ajalt/mordant#8] opened 2020-11-01 19:47 UTC
Mordant 2.0 is a complete rewrite that adds support for markdown rendering, animations, and renderable components like lists and tables. Specifying colors and styles can now be done through static members of the `TextColors` and `TextStyles` enums. You don't need to pass around a `TermColors` instance everywhere; you just need to print the final strings with `Terminal.print` if you want the ANSI codes downsampled.

There's still a lot I'd like to do before a stable release.

- Lots of docs two write, including an mkdocs site
- Multiplatform support. The biggest blocker here is the intellij-markdown dependency. I can contribute native support there if necessary.
- Better animation support, especially for periodic animations like spinners and progress bars. It would probably be helpful to add a DSL for progress updates that can animate a progress bar or spinner, automatically calculate time elapsed/remaining etc. This might be tricky on JS or Native. Maybe it would be best to add kotlinx.coroutines as a dependency rather than try to do concurrency manually.
- Automatically update detected terminal dimensions when the window is resized.
- Maybe get rid of `Terminal.colors`. It's the equivalent of Mordant 1's `TermColors`, but isn't necessary if you use `Terminal.println`. We could simplify a few things if we got rid of it. If we did, you could still use regular `println` instead of the `Terminal` version, you would just need to pass your stings through `Terminal.render` if you want your ANSI codes downsampled.

If anyone can try out the alpha, I'd love to hear your feedback on API, implementation, features, or anything else. You can comment on this issue, start a conversation in the #clikt channel on the kotlinlang slack, or DM me on ASG or kotlinlang slack.

**Comment by robstoll** [comment] 2021-03-08 20:38
Hi @ajalt, stumbled over your library, looks pretty promising :slightly_smiling_face: I am wondering if you plan to break all the experimental interfaces until 2.0 or if they are already safe to use.
Also, I would like to use it in a JS project. I read here https://github.com/ajalt/mordant/issues/3 that you are waiting for a PR to be merged. As far as I can see it is. What is missing that you can release an alpha3 or RC1 or similar which is consumable from a JS project?

**Comment by ajalt** [comment] 2021-03-26 18:17
@robstoll version 2.0.0-beta1 was just released with JS support. There shouldn't be any more major API changes, so give it a try and let me know if it works out for you,

**Comment by mikehearn** [comment] 2021-04-05 18:03
Unfortunately I cannot try this, though I'd like to. Maven can't resolve it due to the missing colormath JARs. Will try it out when that's fixed! The functionality looks great. I'm not sure if it's worth limiting the library too much for JS and Native. At least, the JVM version can be compiled to fast native binaries using GraalVM now. And I'm not sure there is much use for this in the JS world, which has similar libraries already.

**Comment by mikehearn** [comment] 2021-04-07 13:00
OK, it works with Maven (the tool) if you specify `mordant-jvm` as the artifact ID instead of just `mordant`. The reason is, the mordant/colormath POMs are empty, as are the javadoc JARs published alongside them.

I think what's happened here is that Gradle/Kotlin MPP is publishing POMs that aren't actually usable by Maven but in such a way that Maven itself doesn't notice there's anything wrong. It then generates a useless/misleading error message. I suspect this is a side-effect of the desire to use Maven Central as a CDN which would normally insist on having a JAR and a POM, but Gradle wants to only publish its own JSON module file, so it ends up making these empty files. Not ideal.

I think the fix is to provide separate instructions for Maven users that contains the JVM specific artifact, as Maven cannot read the multi-platform lib metadata anyway. I'll open a quick PR.

**Comment by jmfayard** [comment] 2021-05-07 11:09
Hello @ajalt 
could you notify me when `intellij/markdown` and therefore mordant is available on Kotlin/Native?
I want to integrate it to my starter project for building command line tools

https://github.com/jmfayard/kotlin-cli-starter

**Comment by ajalt** [comment] 2021-06-02 17:48
Mordant 2.0.0-beta2 has been released, which includes macosX64 support (@jmfayard)

**Comment by jmfayard** [comment] 2021-06-02 19:00
I can confirm it works, thanks a lot @ajalt

**Comment by elect86** [comment] 2021-09-17 10:17
Just a note,

```val t = Terminal()
t.println(table {
    header { row("CJK", "Emojis") }
    body { row("모ㄹ단ㅌ", "🙊🙉🙈") }
})
```
Show
```
┌──────────┬────────┐
│ CJK      │ Emojis │
├──────────┼────────┤
│ 모ㄹ단ㅌ │ 🙊🙉🙈 │
└──────────┴────────┘
```

**Closed** 2023-07-11 17:57 UTC
