### ISSUE TITLE
Incorrect info.width on Windows terminals

### ISSUE THREAD

**Issue by rossdanderson** [ajalt/mordant#18] opened 2021-05-21 14:52 UTC
First let me say this library and clikt are great, thanks for working on them.

I'm using this in a Kotlin Native project on Windows and getting some odd output for the terminal width. I saw the other ticket regarding max width so added the updateTerminalSize call to no avail.

Below are the results for the following code in various terminals:
```kotlin
        val terminal = Terminal()
        terminal.info.updateTerminalSize()
        println(terminal.info.width)
        terminal.print(
            table {
                header {
                    row("a", "b", "c", "d", "e")
                }

                body {
                    borders = TOM_BOTTOM
                    rowStyles(TextColors.white, TextColors.gray)

                    row {
                        cell("aaaaaaaaaaaaaaaaaa")
                        cell("bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb")
                        cell("ccccccccccccccccccccccccccccccccccccccccccc")
                        cell("dddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
                        cell("eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")
                    }
                }
            }
        )
```

Powershell in Windows Terminal:
![image](https://user-images.githubusercontent.com/3797957/119156105-d09a0380-ba4b-11eb-9e50-0afe03641d8a.png)

CMD in Windows Terminal:
![image](https://user-images.githubusercontent.com/3797957/119156056-c24be780-ba4b-11eb-9733-0cfb84b3eff9.png)

Powershell native:
![image](https://user-images.githubusercontent.com/3797957/119156001-afd1ae00-ba4b-11eb-936c-c870a1a87e2f.png)

**Comment by ajalt** [comment] 2021-05-21 16:23
Thanks for the clear reproduction and screenshots. It will be fixed in the next release.

FYI the initial call to `updateTerminalSize` is only necessary on JVM. It's called automatically on JS and native, since we can use fast C calls on those platforms. On JVM, we have to shell out to an external process, which is slow, so we don't do it automatically.

**Closed** 2021-05-21 16:26 UTC
