### ISSUE TITLE
Feature request: prompt checkbox

### ISSUE THREAD

**Issue by fabriziofortino** [ajalt/mordant#89] opened 2023-02-06 12:56 UTC
Something like this https://www.npmjs.com/package/prompt-checkbox would be extremely useful

**Comment by ajalt** [comment] 2023-02-06 17:16
Hi! I'm closing this as a duplicate of #33.

**Closed by ajalt** 2023-02-06 17:16 UTC

**Comment by fabriziofortino** [comment] 2023-02-06 17:20
@ajalt sorry I completely forgot I have opened an exact same one
